// Code generated by microgen 1.0.4. DO NOT EDIT.

package transport

import types "esgrs/pkg/types"

type (
	GenerateVisualizationRequest struct {
		CompanyID int `json:"company_id"`
	}
	GenerateVisualizationResponse struct {
		Vis types.Visualization `json:"vis"`
	}
)
