version: "3.9"

networks:
  internal:

services:
  data_collection_service:
    container_name: data_collection_service
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: deploy/data_collection_service.Dockerfile
    ports:
      - "8080:8080"
    networks:
      - internal
  data_processing_service:
    container_name: data_processing_service
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: deploy/data_processing_service.Dockerfile
    ports:
      - "8081:8081"
    networks:
      - internal
  reporting_service:
    container_name: reporting_service
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: deploy/reporting_service.Dockerfile
    ports:
      - "8082:8082"
    networks:
      - internal
  visualization_service:
    container_name: visualization_service
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: deploy/visualization_service.Dockerfile
    ports:
      - "8083:8083"
    networks:
      - internal
  postgres:
    container_name: "esgrs_postgres"
    image: postgres:13.3
    environment:
      POSTGRES_DB: "esgrs"
      POSTGRES_USER: "esgrs"
      POSTGRES_PASSWORD: "12345678"
    volumes:
      - ./deploy/migrations:/docker-entrypoint-initdb.d
      - ./deploy/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - internal
