// Code generated by microgen 1.0.4. DO NOT EDIT.

package transport

import types "esgrs/pkg/types"

type (
	GenerateReportRequest struct {
		Result types.ESGRatingResult `json:"result"`
	}
	GenerateReportResponse struct {
		Rep types.Report `json:"rep"`
	}
)
