// Code generated by microgen 1.0.4. DO NOT EDIT.

package transport

import types "esgrs/pkg/types"

type (
	GenerateReportRequest struct {
		CompanyID int `json:"company_id"`
	}
	GenerateReportResponse struct {
		Rep types.Report `json:"rep"`
	}
)
