// Code generated by microgen 1.0.4. DO NOT EDIT.

package transport

import (
	"context"
	reportingservice "esgrs/reporting_service"
	endpoint "github.com/go-kit/kit/endpoint"
	opentracing "github.com/go-kit/kit/tracing/opentracing"
	opentracinggo "github.com/opentracing/opentracing-go"
)

func Endpoints(svc reportingservice.ReportingService) EndpointsSet {
	return EndpointsSet{GenerateReportEndpoint: GenerateReportEndpoint(svc)}
}

// TraceServerEndpoints is used for tracing endpoints on server side.
func TraceServerEndpoints(endpoints EndpointsSet, tracer opentracinggo.Tracer) EndpointsSet {
	return EndpointsSet{GenerateReportEndpoint: opentracing.TraceServer(tracer, "GenerateReport")(endpoints.GenerateReportEndpoint)}
}

func GenerateReportEndpoint(svc reportingservice.ReportingService) endpoint.Endpoint {
	return func(arg0 context.Context, request interface{}) (interface{}, error) {
		req := request.(*GenerateReportRequest)
		res0, res1 := svc.GenerateReport(arg0, req.CompanyID)
		return &GenerateReportResponse{Rep: res0}, res1
	}
}
