// Code generated by microgen 1.0.4. DO NOT EDIT.

package service

import (
	"context"
	types "esgrs/pkg/types"
	service "esgrs/visualization_service"
	log "github.com/go-kit/kit/log"
	"time"
)

// LoggingMiddleware writes params, results and working time of method call to provided logger after its execution.
func LoggingMiddleware(logger log.Logger) Middleware {
	return func(next service.VisualizationService) service.VisualizationService {
		return &loggingMiddleware{
			logger: logger,
			next:   next,
		}
	}
}

type loggingMiddleware struct {
	logger log.Logger
	next   service.VisualizationService
}

func (M loggingMiddleware) GenerateVisualization(arg0 context.Context, arg1 types.ESGRatingResult) (res0 types.Visualization, res1 error) {
	defer func(begin time.Time) {
		M.logger.Log(
			"method", "GenerateVisualization",
			"message", "GenerateVisualization called",
			"request", logGenerateVisualizationRequest{Result: arg1},
			"response", logGenerateVisualizationResponse{Vis: res0},
			"err", res1,
			"took", time.Since(begin))
	}(time.Now())
	return M.next.GenerateVisualization(arg0, arg1)
}

type (
	logGenerateVisualizationRequest struct {
		Result types.ESGRatingResult
	}
	logGenerateVisualizationResponse struct {
		Vis types.Visualization
	}
)
