// Code generated by microgen 1.0.4. DO NOT EDIT.

package service

import (
	"context"
	types "esgrs/pkg/types"
	service "esgrs/reporting_service"
	log "github.com/go-kit/kit/log"
)

// ErrorLoggingMiddleware writes to logger any error, if it is not nil.
func ErrorLoggingMiddleware(logger log.Logger) Middleware {
	return func(next service.ReportingService) service.ReportingService {
		return &errorLoggingMiddleware{
			logger: logger,
			next:   next,
		}
	}
}

type errorLoggingMiddleware struct {
	logger log.Logger
	next   service.ReportingService
}

func (M errorLoggingMiddleware) GenerateReport(ctx context.Context, companyID int) (rep types.Report, err error) {
	defer func() {
		if err != nil {
			M.logger.Log("method", "GenerateReport", "message", err)
		}
	}()
	return M.next.GenerateReport(ctx, companyID)
}
