// Code generated by microgen 1.0.4. DO NOT EDIT.

package service

import (
	"context"
	types "esgrs/pkg/types"
	service "esgrs/reporting_service"
	"fmt"
	log "github.com/go-kit/kit/log"
)

// RecoveringMiddleware recovers panics from method calls, writes to provided logger and returns the error of panic as method error.
func RecoveringMiddleware(logger log.Logger) Middleware {
	return func(next service.ReportingService) service.ReportingService {
		return &recoveringMiddleware{
			logger: logger,
			next:   next,
		}
	}
}

type recoveringMiddleware struct {
	logger log.Logger
	next   service.ReportingService
}

func (M recoveringMiddleware) GenerateReport(ctx context.Context, companyID int) (rep types.Report, err error) {
	defer func() {
		if r := recover(); r != nil {
			M.logger.Log("method", "GenerateReport", "message", r)
			err = fmt.Errorf("%v", r)
		}
	}()
	return M.next.GenerateReport(ctx, companyID)
}
