// Code generated by microgen 1.0.4. DO NOT EDIT.

package transport

import (
	"context"
	types "esgrs/pkg/types"
	opentracing "github.com/go-kit/kit/tracing/opentracing"
	opentracinggo "github.com/opentracing/opentracing-go"
)

// TraceClientEndpoints is used for tracing endpoints on client side.
func TraceClientEndpoints(endpoints EndpointsSet, tracer opentracinggo.Tracer) EndpointsSet {
	return EndpointsSet{
		GetCompanyByIDEndpoint: opentracing.TraceClient(tracer, "GetCompanyByID")(endpoints.GetCompanyByIDEndpoint),
		GetCompanyListEndpoint: opentracing.TraceClient(tracer, "GetCompanyList")(endpoints.GetCompanyListEndpoint),
		GetRawDataEndpoint:     opentracing.TraceClient(tracer, "GetRawData")(endpoints.GetRawDataEndpoint),
	}
}

func (set EndpointsSet) GetCompanyByID(arg0 context.Context, arg1 int) (res0 types.Company, res1 error) {
	request := GetCompanyByIDRequest{Id: arg1}
	response, res1 := set.GetCompanyByIDEndpoint(arg0, &request)
	if res1 != nil {
		return
	}
	return response.(*GetCompanyByIDResponse).Company, res1
}

func (set EndpointsSet) GetRawData(arg0 context.Context, arg1 int) (res0 []types.CriteriaRawData, res1 error) {
	request := GetRawDataRequest{CompanyID: arg1}
	response, res1 := set.GetRawDataEndpoint(arg0, &request)
	if res1 != nil {
		return
	}
	return response.(*GetRawDataResponse).Data, res1
}

func (set EndpointsSet) GetCompanyList(arg0 context.Context) (res0 []types.Company, res1 error) {
	request := GetCompanyListRequest{}
	response, res1 := set.GetCompanyListEndpoint(arg0, &request)
	if res1 != nil {
		return
	}
	return response.(*GetCompanyListResponse).Companies, res1
}
