// Code generated by microgen 1.0.4. DO NOT EDIT.

package transport

import types "esgrs/pkg/types"

type (
	GetCompanyByIDRequest struct {
		Id int `json:"id"`
	}
	GetCompanyByIDResponse struct {
		Company types.Company `json:"company"`
	}

	GetRawDataRequest struct {
		CompanyID int `json:"company_id"`
	}
	GetRawDataResponse struct {
		Data []types.CriteriaRawData `json:"data"`
	}

	// Formal exchange type, please do not delete.
	GetCompanyListRequest  struct{}
	GetCompanyListResponse struct {
		Companies []types.Company `json:"companies"`
	}
)
