// Code generated by microgen 1.0.4. DO NOT EDIT.

package transport

import types "esgrs/pkg/types"

type (
	CollectDataRequest struct {
		Company types.Company `json:"company"`
	}
	CollectDataResponse struct {
		Data []types.CriteriaData `json:"data"`
	}

	// Formal exchange type, please do not delete.
	GetCompanyListRequest  struct{}
	GetCompanyListResponse struct {
		Companies []types.Company `json:"companies"`
	}
)
