// Code generated by microgen 1.0.4. DO NOT EDIT.

package service

import (
	"context"
	service "esgrs/data_collection_service"
	types "esgrs/pkg/types"
	log "github.com/go-kit/kit/log"
)

// ErrorLoggingMiddleware writes to logger any error, if it is not nil.
func ErrorLoggingMiddleware(logger log.Logger) Middleware {
	return func(next service.DataCollectionService) service.DataCollectionService {
		return &errorLoggingMiddleware{
			logger: logger,
			next:   next,
		}
	}
}

type errorLoggingMiddleware struct {
	logger log.Logger
	next   service.DataCollectionService
}

func (M errorLoggingMiddleware) CollectData(ctx context.Context, company types.Company) (data []types.CriteriaData, err error) {
	defer func() {
		if err != nil {
			M.logger.Log("method", "CollectData", "message", err)
		}
	}()
	return M.next.CollectData(ctx, company)
}

func (M errorLoggingMiddleware) GetCompanyList(ctx context.Context) (companies []types.Company, err error) {
	defer func() {
		if err != nil {
			M.logger.Log("method", "GetCompanyList", "message", err)
		}
	}()
	return M.next.GetCompanyList(ctx)
}
