// Code generated by microgen 1.0.4. DO NOT EDIT.

package service

import (
	"context"
	service "esgrs/data_collection_service"
	types "esgrs/pkg/types"
	log "github.com/go-kit/kit/log"
	"time"
)

// LoggingMiddleware writes params, results and working time of method call to provided logger after its execution.
func LoggingMiddleware(logger log.Logger) Middleware {
	return func(next service.DataCollectionService) service.DataCollectionService {
		return &loggingMiddleware{
			logger: logger,
			next:   next,
		}
	}
}

type loggingMiddleware struct {
	logger log.Logger
	next   service.DataCollectionService
}

func (M loggingMiddleware) GetCompanyByID(arg0 context.Context, arg1 int) (res0 types.Company, res1 error) {
	defer func(begin time.Time) {
		M.logger.Log(
			"method", "GetCompanyByID",
			"message", "GetCompanyByID called",
			"request", logGetCompanyByIDRequest{Id: arg1},
			"response", logGetCompanyByIDResponse{Company: res0},
			"err", res1,
			"took", time.Since(begin))
	}(time.Now())
	return M.next.GetCompanyByID(arg0, arg1)
}

func (M loggingMiddleware) GetRawData(arg0 context.Context, arg1 int) (res0 []types.CriteriaRawData, res1 error) {
	defer func(begin time.Time) {
		M.logger.Log(
			"method", "GetRawData",
			"message", "GetRawData called",
			"request", logGetRawDataRequest{CompanyID: arg1},
			"response", logGetRawDataResponse{Data: res0},
			"err", res1,
			"took", time.Since(begin))
	}(time.Now())
	return M.next.GetRawData(arg0, arg1)
}

func (M loggingMiddleware) GetCompanyList(arg0 context.Context) (res0 []types.Company, res1 error) {
	defer func(begin time.Time) {
		M.logger.Log(
			"method", "GetCompanyList",
			"message", "GetCompanyList called",
			"response", logGetCompanyListResponse{Companies: res0},
			"err", res1,
			"took", time.Since(begin))
	}(time.Now())
	return M.next.GetCompanyList(arg0)
}

type (
	logGetCompanyByIDRequest struct {
		Id int
	}
	logGetCompanyByIDResponse struct {
		Company types.Company
	}
	logGetRawDataRequest struct {
		CompanyID int
	}
	logGetRawDataResponse struct {
		Data []types.CriteriaRawData
	}
	logGetCompanyListResponse struct {
		Companies []types.Company
	}
)
