// Code generated by microgen 1.0.4. DO NOT EDIT.

package service

import (
	"context"
	service "esgrs/data_collection_service"
	types "esgrs/pkg/types"
	log "github.com/go-kit/kit/log"
	"time"
)

// LoggingMiddleware writes params, results and working time of method call to provided logger after its execution.
func LoggingMiddleware(logger log.Logger) Middleware {
	return func(next service.DataCollectionService) service.DataCollectionService {
		return &loggingMiddleware{
			logger: logger,
			next:   next,
		}
	}
}

type loggingMiddleware struct {
	logger log.Logger
	next   service.DataCollectionService
}

func (M loggingMiddleware) CollectData(arg0 context.Context, arg1 types.Company) (res0 []types.CriteriaData, res1 error) {
	defer func(begin time.Time) {
		M.logger.Log(
			"method", "CollectData",
			"message", "CollectData called",
			"request", logCollectDataRequest{Company: arg1},
			"response", logCollectDataResponse{Data: res0},
			"err", res1,
			"took", time.Since(begin))
	}(time.Now())
	return M.next.CollectData(arg0, arg1)
}

func (M loggingMiddleware) GetCompanyList(arg0 context.Context) (res0 []types.Company, res1 error) {
	defer func(begin time.Time) {
		M.logger.Log(
			"method", "GetCompanyList",
			"message", "GetCompanyList called",
			"response", logGetCompanyListResponse{Companies: res0},
			"err", res1,
			"took", time.Since(begin))
	}(time.Now())
	return M.next.GetCompanyList(arg0)
}

type (
	logCollectDataRequest struct {
		Company types.Company
	}
	logCollectDataResponse struct {
		Data []types.CriteriaData
	}
	logGetCompanyListResponse struct {
		Companies []types.Company
	}
)
