// Code generated by microgen 1.0.4. DO NOT EDIT.

package service

import service "esgrs/data_processing_service"

// Service middleware (closure).
type Middleware func(service.DataProcessingService) service.DataProcessingService
