// Code generated by microgen 1.0.4. DO NOT EDIT.

package service

import (
	"context"
	service "esgrs/data_processing_service"
	types "esgrs/pkg/types"
	"fmt"
	log "github.com/go-kit/kit/log"
)

// RecoveringMiddleware recovers panics from method calls, writes to provided logger and returns the error of panic as method error.
func RecoveringMiddleware(logger log.Logger) Middleware {
	return func(next service.DataProcessingService) service.DataProcessingService {
		return &recoveringMiddleware{
			logger: logger,
			next:   next,
		}
	}
}

type recoveringMiddleware struct {
	logger log.Logger
	next   service.DataProcessingService
}

func (M recoveringMiddleware) ProcessData(ctx context.Context, data []types.CriteriaData) (result types.ESGRatingResult, err error) {
	defer func() {
		if r := recover(); r != nil {
			M.logger.Log("method", "ProcessData", "message", r)
			err = fmt.Errorf("%v", r)
		}
	}()
	return M.next.ProcessData(ctx, data)
}
