// Code generated by microgen 1.0.4. DO NOT EDIT.

package transport

import (
	"context"
	types "esgrs/pkg/types"
	opentracing "github.com/go-kit/kit/tracing/opentracing"
	opentracinggo "github.com/opentracing/opentracing-go"
)

// TraceClientEndpoints is used for tracing endpoints on client side.
func TraceClientEndpoints(endpoints EndpointsSet, tracer opentracinggo.Tracer) EndpointsSet {
	return EndpointsSet{ProcessDataEndpoint: opentracing.TraceClient(tracer, "ProcessData")(endpoints.ProcessDataEndpoint)}
}

func (set EndpointsSet) ProcessData(arg0 context.Context, arg1 []types.CriteriaData) (res0 types.ESGRatingResult, res1 error) {
	request := ProcessDataRequest{Data: arg1}
	response, res1 := set.ProcessDataEndpoint(arg0, &request)
	if res1 != nil {
		return
	}
	return response.(*ProcessDataResponse).Result, res1
}
