// Code generated by microgen 1.0.4. DO NOT EDIT.

package transport

import (
	"context"
	"fmt"
	endpoint "github.com/go-kit/kit/endpoint"
	metrics "github.com/go-kit/kit/metrics"
	opentracing "github.com/go-kit/kit/tracing/opentracing"
	opentracinggo "github.com/opentracing/opentracing-go"
	"time"
)

// EndpointsSet implements DataProcessingService API and used for transport purposes.
type OneToManyStreamEndpoint func(req interface{}, stream interface{}) error

type ManyToManyStreamEndpoint func(stream interface{}) error

type ManyToOneStreamEndpoint func(stream interface{}) error

type EndpointsSet struct {
	GetProcessedDataEndpoint endpoint.Endpoint
}

func InstrumentingEndpoints(endpoints EndpointsSet, tracer opentracinggo.Tracer) EndpointsSet {
	return EndpointsSet{GetProcessedDataEndpoint: opentracing.TraceServer(tracer, "GetProcessedData")(endpoints.GetProcessedDataEndpoint)}
}

func LatencyMiddleware(dur metrics.Histogram, methodName string) endpoint.Middleware {
	return func(next endpoint.Endpoint) endpoint.Endpoint {
		dur := dur.With("method", methodName)
		return func(ctx context.Context, request interface{}) (response interface{}, err error) {
			defer func(begin time.Time) {
				dur.With("success", fmt.Sprint(err == nil)).Observe(time.Since(begin).Seconds())
			}(time.Now())
			return next(ctx, request)
		}
	}
}

func RequestFrequencyMiddleware(freq metrics.Gauge, methodName string) endpoint.Middleware {
	return func(next endpoint.Endpoint) endpoint.Endpoint {
		freq := freq.With("method", methodName)
		return func(ctx context.Context, request interface{}) (interface{}, error) {
			freq.Add(1)
			response, err := next(ctx, request)
			freq.Add(-1)
			return response, err
		}
	}
}
