// Code generated by microgen 1.0.4. DO NOT EDIT.

package transport

import types "esgrs/pkg/types"

type (
	GetProcessedDataRequest struct {
		CompanyID int `json:"company_id"`
	}
	GetProcessedDataResponse struct {
		Result types.ESGRatingResult `json:"result"`
	}
)
