// Code generated by microgen 1.0.4. DO NOT EDIT.

package transport

import types "esgrs/pkg/types"

type (
	ProcessDataRequest struct {
		Data []types.CriteriaData `json:"data"`
	}
	ProcessDataResponse struct {
		Result types.ESGRatingResult `json:"result"`
	}
)
