// Code generated by microgen 1.0.4. DO NOT EDIT.

package transport

import (
	"context"
	dataprocessingservice "esgrs/data_processing_service"
	endpoint "github.com/go-kit/kit/endpoint"
	opentracing "github.com/go-kit/kit/tracing/opentracing"
	opentracinggo "github.com/opentracing/opentracing-go"
)

func Endpoints(svc dataprocessingservice.DataProcessingService) EndpointsSet {
	return EndpointsSet{ProcessDataEndpoint: ProcessDataEndpoint(svc)}
}

// TraceServerEndpoints is used for tracing endpoints on server side.
func TraceServerEndpoints(endpoints EndpointsSet, tracer opentracinggo.Tracer) EndpointsSet {
	return EndpointsSet{ProcessDataEndpoint: opentracing.TraceServer(tracer, "ProcessData")(endpoints.ProcessDataEndpoint)}
}

func ProcessDataEndpoint(svc dataprocessingservice.DataProcessingService) endpoint.Endpoint {
	return func(arg0 context.Context, request interface{}) (interface{}, error) {
		req := request.(*ProcessDataRequest)
		res0, res1 := svc.ProcessData(arg0, req.Data)
		return &ProcessDataResponse{Result: res0}, res1
	}
}
